// Front-end/src/app/components/navbar/navbar.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar',
  imports: [CommonModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  mobileMenuOpen = false;
  menuItems = ['Home', 'Our Coffees', 'About Us'];
}
<!-- <nav class=" absolute top-0 left-0 w-full z-50 flex justify-between items-center bg-transparent  text-black px-8 py-4">
    <div class="w-9 h-9">
        <img src="logo.png" alt="logo" />
    </div>

    <div class="flex gap-8">
        <div *ngFor="let item of menuItems" class=" text-white hover:text-gray-300 hover:cursor-pointer">
            {{ item }}
        </div>
    </div>

    <div class="flex gap-4">
        <button class="px-4 py-2 bg-white text-black rounded-lg hover:bg-gray-200 transition">
            Login
        </button>
        <button class="px-4 py-2 text-white border border-white rounded-lg hover:bg-white hover:text-black transition">
            Sign Up
        </button>
    </div>
</nav> -->
<nav class="absolute top-0 left-0 w-full z-50 bg-transparent text-white px-4 sm:px-8 py-4 flex justify-between items-center">
  <!-- Logo -->
  <div class="w-12 h-16">
    <img src="logo.png" alt="logo" class="w-full h-full object-contain" />
  </div>

  <!-- Desktop menu -->
  <div class="hidden  md:flex gap-6 lg:gap-8 ml-auto">
    <div *ngFor="let item of menuItems" class="hover:text-peach  cursor-pointer font-instrument-sans transition">
      {{ item }}
    </div>
  </div>

  <!-- Desktop buttons -->
  <div class="hidden md:flex gap-3 ml-8">
    <button class="px-6 py-2 
 bg-white text-black rounded-lg hover:bg-peach font-instrument-sans  transition">
      Login
    </button>
    <button class="px-4 py-2 h-10
 border border-white text-white rounded-lg hover:bg-peach hover:border-peach hover:text-black font-instrument-sans transition">
      Sign Up
    </button>
  </div>

  <!-- Mobile menu button -->
  <div class="md:hidden">
    <button (click)="mobileMenuOpen = !mobileMenuOpen" class="focus:outline-none">
      <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
      </svg>
    </button>
  </div>

  <!-- Mobile menu -->
  <div *ngIf="mobileMenuOpen" class="absolute top-full left-0 w-full bg-stone-900/80 flex flex-col items-center gap-4 py-4 md:hidden">
    <div *ngFor="let item of menuItems" class="text-white hover:text-gray-300 cursor-pointer transition">
      {{ item }}
    </div>
    <button class="w-3/4 px-4 py-2 bg-white text-black rounded-lg hover:bg-gray-200 transition">
      Login
    </button>
    <button class="w-3/4 px-4 py-2 border border-white text-white rounded-lg hover:bg-white hover:text-black transition">
      Sign Up
    </button>
  </div>
</nav>

// frontend/src/components/layouts/Navbar.jsx
import { useState } from "react";
import { Link } from "react-router-dom";
export default function Navbar() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const menuItems = ["Home", "About", "Services", "Contact"];

  return (
    <nav className="absolute top-0 left-0 w-full z-50 bg-transparent text-white px-4 sm:px-8 py-4 flex justify-between items-center">
      {/* Logo */}
      <div className="w-12 h-16">
        <img
          src="/assets/logo.png"
          alt="logo"
          className="w-full h-full object-contain"
        />
      </div>

      {/* Desktop menu */}
      <div className="hidden md:flex gap-6 lg:gap-8 ml-auto">
        {menuItems.map((item) => (
          <div
            key={item}
            className="hover:text-peach cursor-pointer font-instrument-sans transition"
          >
            {item}
          </div>
        ))}
      </div>

      {/* Desktop buttons */}
      <div className="hidden md:flex gap-3 ml-8">
        <Link
          to="/"
          className="px-6 py-2 bg-white text-black rounded-lg hover:bg-peach font-instrument-sans transition inline-flex items-center justify-center"
        >
          Login
        </Link>

        <Link
          to="/"
          className="px-4 py-2 h-10 border border-white text-white rounded-lg hover:bg-peach hover:border-peach hover:text-black font-instrument-sans transition inline-flex items-center justify-center"
        >
          Sign Up
        </Link>

      </div>

      {/* Mobile menu button */}
      <div className="md:hidden">
        <button
          onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
          className="focus:outline-none"
        >
          <svg
            className="w-6 h-6 text-white"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>
        </button>
      </div>

      {/* Mobile menu */}
      {mobileMenuOpen && (
        <div className="absolute top-full left-0 w-full bg-stone-900/80 flex flex-col items-center gap-4 py-4 md:hidden">
          {menuItems.map((item) => (
            <div
              key={item}
              className="text-white hover:text-gray-300 cursor-pointer transition"
            >
              {item}
            </div>
          ))}
          <button className="w-3/4 px-4 py-2 bg-white text-black rounded-lg hover:bg-gray-200 transition">
            Login
          </button>
          <button className="w-3/4 px-4 py-2 border border-white text-white rounded-lg hover:bg-white hover:text-black transition">
            Sign Up
          </button>
        </div>
      )}
    </nav>
  );
}
