// frontend/src/components/common/Navbar.jsx
import { useContext, useState } from "react";
import { Link } from "react-router-dom";
import { useNavigate } from "react-router-dom";
import AuthContext from "../../contexts/AuthContext";

export default function Navbar() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const navigate = useNavigate();
  const { isAuthenticated, logout, user } = useContext(AuthContext);

  const menuItems = [
    {
      name: "Our coffee",
      link: "/coffees"
    },
    {
      name: "About Us",
      link: "#"
    },
    {
      name: "Subscribe",
      link: "#"
    }
  ];

  const handleLogout = () => {
    if (window.confirm("Are you sure you want to logout?")) {
      logout();
      navigate("/");
    }
  };

  return (
    <nav className="absolute top-0 left-0 w-full z-50 bg-transparent text-white px-4 sm:px-8 py-4 flex justify-between items-center">
      {/* Logo */}
      <div onClick={() => navigate("/")} className="w-12 h-16 cursor-pointer">
        <img 
          src="/assets/logo.png"
          alt="logo"
          className="w-full h-full object-contain"
        />
      </div>

      {/* Desktop menu */}
      <div className="hidden md:flex gap-6 lg:gap-8 ml-auto">
        {menuItems.map((item) => (
          <div
            key={item.name}
            className="hover:text-peach cursor-pointer font-instrument-sans transition"
          >
            <a href={item.link}>{item.name}</a>
          </div>
        ))}
      </div>

      {/* Desktop buttons */}
      <div className="hidden md:flex items-center gap-3 ml-8">
        {!isAuthenticated ? (
          <>
            <Link
              to="/login"
              className="px-6 py-2 bg-white text-black rounded-lg hover:bg-peach font-instrument-sans transition inline-flex items-center justify-center"
            >
              Login
            </Link>
            <Link
              to="/register"
              className="px-4 py-2 h-10 border border-white text-white rounded-lg hover:bg-peach hover:border-peach hover:text-black font-instrument-sans transition inline-flex items-center justify-center"
            >
              Sign Up
            </Link>
          </>
        ) : (
          <>
            <button
              onClick={handleLogout}
              className="px-4 py-2 h-10 border border-white text-white rounded-lg hover:bg-peach hover:border-peach hover:text-black font-instrument-sans transition inline-flex items-center justify-center"
            >
              Logout
            </button>
            <Link
              to="/profile"
              className="w-10 h-10 rounded-full border border-white flex items-center justify-center hover:bg-white/20 transition"
              title="Profile"
            >
              <svg className="w-5 h-5 text-white" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 12c2.7 0 4.5-2.1 4.5-4.5S14.7 3 12 3 7.5 5.1 7.5 7.5 9.3 12 12 12zm0 2c-3 0-9 1.5-9 4.5V21h18v-2.5C21 15.5 15 14 12 14z" />
              </svg>
            </Link>
            <Link
              to="/cart"
              className="w-10 h-10 rounded-full border border-white flex items-center justify-center hover:bg-white/20 transition"
              title="Cart"
            >
              <svg className="w-5 h-5 text-white" viewBox="0 0 24 24" fill="currentColor">
                <path d="M7 18c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm10 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zM7.2 6l.3 2h10.9c.6 0 1.1.4 1.2 1l.9 5.1c.1.7-.4 1.4-1.2 1.4H8.1c-.6 0-1.1-.4-1.2-1L5.3 4H3V2h3.1c.6 0 1.1.4 1.2 1l.3 1H21v2H7.2z" />
              </svg>
            </Link>
          </>
        )}
      </div>

      {/* Mobile menu button */}
      <div className="md:hidden">
        <button
          onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
          className="focus:outline-none"
        >
          <svg
            className="w-6 h-6 text-white"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>
        </button>
      </div>

      {/* Mobile menu */}
      {mobileMenuOpen && (
        <div className="absolute top-full left-0 w-full bg-stone-900/80 flex flex-col items-center gap-4 py-4 md:hidden">
          {menuItems.map((item) => (
            <div
              key={item.name}
              className="text-white hover:text-gray-300 cursor-pointer transition"
            >
              <a href={item.link}>{item.name}</a>
            </div>
          ))}
          {!isAuthenticated ? (
            <>
              <Link
                to="/login"
                className="px-6 py-2 bg-white text-black rounded-lg hover:bg-peach font-instrument-sans transition inline-flex items-center justify-center"
              >
                Login
              </Link>
              <Link
                to="/register"
                className="px-4 py-2 h-10 border border-white text-white rounded-lg hover:bg-peach hover:border-peach hover:text-black font-instrument-sans transition inline-flex items-center justify-center"
              >
                Sign Up
              </Link>
            </>
          ) : (
            <>
              <button
                onClick={handleLogout}
                className="px-6 py-2 bg-white text-black rounded-lg hover:bg-peach font-instrument-sans transition inline-flex items-center justify-center"
              >
                Logout
              </button>
              <Link
                to="/profile"
                className="px-6 py-2 bg-white text-black rounded-lg hover:bg-peach font-instrument-sans transition inline-flex items-center justify-center"
              >
                Profile
              </Link>
              <Link
                to="/cart"
                className="px-6 py-2 bg-white text-black rounded-lg hover:bg-peach font-instrument-sans transition inline-flex items-center justify-center"
              >
                Cart
              </Link>
            </>
          )}
        </div>
      )}
    </nav>
  );
}

// Front-end/src/app/components/navbar/navbar.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar',
  imports: [CommonModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  mobileMenuOpen = false;
  menuItems = ['Home', 'Our Coffees', 'About Us'];
}
<!-- <nav class=" absolute top-0 left-0 w-full z-50 flex justify-between items-center bg-transparent  text-black px-8 py-4">
    <div class="w-9 h-9">
        <img src="logo.png" alt="logo" />
    </div>

    <div class="flex gap-8">
        <div *ngFor="let item of menuItems" class=" text-white hover:text-gray-300 hover:cursor-pointer">
            {{ item }}
        </div>
    </div>

    <div class="flex gap-4">
        <button class="px-4 py-2 bg-white text-black rounded-lg hover:bg-gray-200 transition">
            Login
        </button>
        <button class="px-4 py-2 text-white border border-white rounded-lg hover:bg-white hover:text-black transition">
            Sign Up
        </button>
    </div>
</nav> -->
<nav class="absolute top-0 left-0 w-full z-50 bg-transparent text-white px-4 sm:px-8 py-4 flex justify-between items-center">
  <!-- Logo -->
  <div class="w-12 h-16">
    <img src="logo.png" alt="logo" class="w-full h-full object-contain" />
  </div>

  <!-- Desktop menu -->
  <div class="hidden  md:flex gap-6 lg:gap-8 ml-auto">
    <div *ngFor="let item of menuItems" class="hover:text-peach  cursor-pointer font-instrument-sans transition">
      {{ item }}
    </div>
  </div>

  <!-- Desktop buttons -->
  <div class="hidden md:flex gap-3 ml-8">
    <button class="px-6 py-2 
 bg-white text-black rounded-lg hover:bg-peach font-instrument-sans  transition">
      Login
    </button>
    <button class="px-4 py-2 h-10
 border border-white text-white rounded-lg hover:bg-peach hover:border-peach hover:text-black font-instrument-sans transition">
      Sign Up
    </button>
  </div>

  <!-- Mobile menu button -->
  <div class="md:hidden">
    <button (click)="mobileMenuOpen = !mobileMenuOpen" class="focus:outline-none">
      <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
      </svg>
    </button>
  </div>

  <!-- Mobile menu -->
  <div *ngIf="mobileMenuOpen" class="absolute top-full left-0 w-full bg-stone-900/80 flex flex-col items-center gap-4 py-4 md:hidden">
    <div *ngFor="let item of menuItems" class="text-white hover:text-gray-300 cursor-pointer transition">
      {{ item }}
    </div>
    <button class="w-3/4 px-4 py-2 bg-white text-black rounded-lg hover:bg-gray-200 transition">
      Login
    </button>
    <button class="w-3/4 px-4 py-2 border border-white text-white rounded-lg hover:bg-white hover:text-black transition">
      Sign Up
    </button>
  </div>
</nav>
